kumuluzee:
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:postgresql://postgres-customers:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20
