FROM openjdk:8-jre-alpine

RUN mkdir /app

WORKDIR /app

ADD $TRAVIS_BUILD_DIR/ws-adverts/target/ws-adverts-1.0-SNAPSHOT.jar /app

EXPOSE 8080

CMD ["java", "-jar", "/app/ws-adverts-1.0-SNAPSHOT.jar"]
