FROM openjdk:8-jre

RUN apt-get -qq update
RUN apt-get -qq -y install supervisor
RUN apt-get -qq -y install procps
RUN apt-get -qq -y install net-tools
RUN apt-get -qq -y install telnet
RUN apt-get -qq -y install lynx

RUN mkdir /app

WORKDIR /app

ADD $TRAVIS_BUILD_DIR/ws-adverts/target/ws-adverts-1.0-SNAPSHOT.jar /app

EXPOSE 8082

CMD ["java", "-jar", "/app/ws-adverts-1.0-SNAPSHOT.jar"]
