kumuluzee:
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:postgresql://postgres:5432/adverts
      username: postgres
      password: postgres
      max-pool-size: 20
  server:
      base-url: http://localhost:8081
      http:
        port: 8081
  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 20
    ping-interval: 15

