kumuluzee:
  name: ws-orders
  env:
    name: dev
  version: 1.0.0
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:postgresql://postgresql:5432/adverts
      username: postgres
      password: postgres
      max-pool-size: 20
  server:
      base-url: http://localhost:8081
      http:
        port: 8081
  discovery:
    etcd:
      hosts: http://etcd:2379
    ttl: 20
    ping-interval: 15
    cluster: cluster-1
  orders-url: http://35.198.158.135
  adverts-url: http://35.198.120.63


