kumuluzee:
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:postgresql://postgres:5432/adverts
      username: postgres
      password: postgres
      max-pool-size: 20
  server:
      base-url: http://localhost:8081
      http:
        port: 8081
  discovery:
      consul:
          agent: http://consul:8500
