kumuluzee:
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:mysql://localhost:3306/
      username: root
      password: rok123
      max-pool-size: 20
  server:
      base-url: http://localhost:8081
      http:
        port: 8081
