kumuluzee:
  name: ws-orders
  env:
    name: dev
  version: 1.0.0
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:postgresql://localhost:5432/adverts
      username: postgres
      password: postgres
      max-pool-size: 20
  server:
      base-url: http://localhost:8081
      http:kumuluzee:
             name: ws-orders
             env:
               name: dev
             version: 1.0.0
             datasources:
               - jndi-name: jdbc/advertsDS
                 connection-url: jdbc:postgresql://postgresql:5432/adverts
                 username: postgres
                 password: postgres
                 max-pool-size: 20
             server:
                 base-url: http://localhost:8081
                 http:
                   port: 8081
             discovery:
               etcd:
                 hosts: http://etcd:2379
               ttl: 20
               ping-interval: 15
               cluster: cluster-1
             orders-url: http://ws-orders:8081
             adverts-url: http://ws-adverts:8082


        port: 8081
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 20
    ping-interval: 15
    cluster: cluster-1
  orders-url: http://localhost:8081
  adverts-url: http://localhost:8082