kumuluzee:
  datasources:
    - jndi-name: jdbc/advertsDS
      connection-url: jdbc:postgresql://postgres:5432/adverts
      username: postgres
      password: postgres
      max-pool-size: 20
  server:
      base-url: http://localhost:8082
      http:
        port: 8082
  discovery:
      consul:
          agent: http://consul:8500
  name: adverts-service
    env:
      name: dev
    version: 1.2.3
